# SPDX-FileCopyrightText: 2023 Stefan Schmidt <stefan@datenfreihafen.org>
#
# SPDX-License-Identifier: ISC

name: Basic compile test for wpan-tools
on: push

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install libnl-3-dev libnl-genl-3-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: distcheck
      run: make distcheck
