# SPDX-FileCopyrightText: 2023 Stefan Schmidt <stefan@datenfreihafen.org>
#
# SPDX-License-Identifier: ISC

name: Basic compile test for wpan-tools
on: push

jobs:
  compile:
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.cc }}
    strategy:
      matrix:
        cc: [gcc, clang]
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install libnl-3-dev libnl-genl-3-dev ${{ matrix.cc }}
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: distcheck
      run: make distcheck
