# SPDX-FileCopyrightText: 2023 Stefan Schmidt <stefan@datenfreihafen.org>
#
# SPDX-License-Identifier: ISC

name: Check for REUSE compliance of wpan-tools
on: push

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Install reuse tool
      run: pip3 install reuse
    - name: Run reuse lint
      run: reuse lint
    - name: Create SBOM
      run: reuse spdx > sbom.txt
